---
- hosts: all
  vars:
    girder_worker_virtualenv: "/opt/worker_venv"
    girder_worker_user: "{{ ansible_user_id }}"
    celery_executable: "{{ girder_worker_virtualenv }}/bin/celery"

  tasks:
    - name: Install Girder Worker system dependencies
      apt:
        name: "{{ item }}"
        update_cache: true
      become: yes
      become_user: root
      with_items:
        - python3-pip
        - virtualenv
        - libssl-dev
        - build-essential
        - pkg-config
        - cmake
        - golang
    - name: Install Rust
      shell: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y
      become: yes
      become_user: root

    - name: Clone amazon-efs-utils repository
      git:
        repo: https://github.com/aws/efs-utils.git
        dest: /tmp/efs-utils

    - name: Build amazon-efs-utils
      command: /bin/bash -c 'source /root/.cargo/env && /tmp/efs-utils/build-deb.sh'
      args:
        chdir: /tmp/efs-utils
      become: yes
      become_user: root

    - name: Install amazon-efs-utils
      command: /bin/bash -c 'apt-get -y install /tmp/efs-utils/build/amazon-efs-utils*deb'
      become: yes
      become_user: root

    - block:
      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu jammy stable
          state: present

      - name: Update apt and install docker-ce
        apt:
          name: docker-ce
          state: latest
          update_cache: true
      become: yes
      become_user: root

    - name: Install Girder Worker with Slicer CLI Web
      pip:
        name: "girder-slicer-cli-web[worker]>=5.0.0a8.dev52"
        state: latest
        virtualenv: "{{ girder_worker_virtualenv }}"
      become: yes
      become_user: root

    - name: Install large-image worker packages
      ansible.builtin.pip:
        name: "girder-large-image-annotation[tasks]>=1.32.5a123"
        extra_args: "--find-links=https://girder.github.io/large_image_wheels"
        state: latest
        virtualenv: "{{ girder_worker_virtualenv }}"
      become: yes
      become_user: root

    - name: Downgrade urllib3 (docker-py does not yet support urllib3>=2)
      pip:
        name: "urllib3<2"
        state: latest
        virtualenv: "{{ girder_worker_virtualenv }}"
      become: yes
      become_user: root

    - name: Downgrade requests (newer versions break girder-client)
      pip:
        name: "requests==2.26.0"
        state: latest
        virtualenv: "{{ girder_worker_virtualenv }}"
      become: yes
      become_user: root

    - name: Create mount point for assetstore
      ansible.builtin.file:
        path: /assetstore
        state: directory
        mode: '0755'
      become: yes
      become_user: root

    - block:
      - name: Install systemd service
        template:
          src: "girder_worker.service.j2"
          dest: "/etc/systemd/system/girder_worker.service"

      - name: Reload systemd units
        systemd:
          name: girder_worker
          daemon_reload: yes

      - name: Enable/Disable Girder service on boot
        service:
          name: girder_worker
          enabled: yes
      become: yes
      become_user: root
